AllCops:
  Exclude:
    - db/migrate/**/*
    - db/schema.rb
    - config/**/*
    - script/**/*
    - bin/**/*
    - test/**/*
    - app/admin/**/*
    - app/channels/**/*
    - app/jobs/**/*
    - node_modules/**/*
    - Gemfile
    - Rakefile
    - config.ru

require:
  - rubocop-rails

Style/Encoding:
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/InlineComment:
  Description: 'Avoid inline comments.'
  Enabled: false

Layout/LineLength:
  Description: 'Limit lines to 110 characters.'
  Max: 200 # Already adjusted.

Metrics/MethodLength:
  Description: 'Allow methods to have more lines.'
  Max: 70 # Increased from 50 to 70 for methods like `create`.

Metrics/ClassLength:
  Description: 'Allow classes to have more lines of code.'
  Max: 250 # Already adjusted.

Metrics/AbcSize:
  Description: 'Allow higher ABC size for complex methods.'
  Max: 90 # Increased from 55 to 90
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'



Metrics/CyclomaticComplexity:
  Description: 'Allow higher Cyclomatic Complexity for methods.'
  Max: 20 # Increased from 15.

Metrics/PerceivedComplexity:
  Description: 'Allow higher Perceived Complexity for methods.'
  Max: 20 # Increased from 15.

Style/FrozenStringLiteralComment:
  Description: To help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false

Style/WordArray:
  Description: 'Use %w or %W for arrays of words.'
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Lint/UnusedBlockArgument:
  AutoCorrect: false

Lint/UnusedMethodArgument:
  AutoCorrect: false

Rails/HasAndBelongsToMany:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false
